services:
  # ------------------
  # Edge proxy (remote)
  # ------------------
  caddy:
    image: caddy:2
    container_name: prod-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped

  # ------------------
  # Next.js (prod mode)
  # ------------------
  web:
    image: meigangwen/website-web
    container_name: prod-web
    environment:
      - NODE_ENV=production
      - PORT=3000
    stdin_open: true
    tty: true

volumes:
  caddy_data:
  caddy_config:
